# Proxy Astro Asset Bundles
[[redirects]]
  from = "/_astro/*"
  to = "https://soggyinkgames-investors.netlify.app/_astro/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*.css"
  to = "https://soggyinkgames-investors.netlify.app/:splat"
  status = 200
  force = true

# Proxy Investor Subpath Routes
[[redirects]]
  from = "/investors"
  to = "https://soggyinkgames-investors.netlify.app/"
  status = 200
  force = true

[[redirects]]
  from = "/investors/*"
  to = "https://soggyinkgames-investors.netlify.app/:splat"
  status = 200
  force = true
